// Get semua Users //
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBZGUgdXBkYXRlIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3NDUyOTQyMTQsImV4cCI6MTc0NTMwMTQxNH0.IXxIWu13hRP7ydcbz_Tu149cnGP4HoGAErYmxoMqhwI

// Users By nip //
###
GET http://localhost:5000/users/12345


// Register Users dan admin//
###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "nip": "332323222",
    "name": "Ade darma",
    "email": "ade@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "user"
}


// Edit Users dan admin //
###
PATCH   http://localhost:5000/users/332323222
Content-Type: application/json

{
    "nip": "12345",
    "name": "Ade darma",
    "email": "ade@gmail.com",
    "password": "12345",
    "confPassword": "12345",
    "role": "user"
}


// Login Users dan Admin //
###
POST  http://localhost:5000/login
Content-Type: application/json

{
    "nip": "332323222",
    "password": "12345"
}


// Get Token Dari Akun //
###
GET   http://localhost:5000/token


// Delete Users dan Admin Berdasarkan nip //
###
DELETE    http://localhost:5000/users/8a932ec1-f236-4065-a069-ab79df2297e2


// Logout akun //   
###
DELETE http://localhost:5000/logout




DOSEN
###
GET http://localhost:5000/dosen/2


###
POST http://localhost:5000/dosen
Content-Type: application/json

{
    "nip": "1122334455",
    "name": "Rizky Putra Fhonna, S.T., M.Kom",
    "keahlian": "website",
    "jabatan": "Ketua Prodi",
    "status": "aktif"
}


###
PATCH  http://localhost:5000/dosen/1
Content-Type: application/json

{
    "nip": "1122334455",
    "name": "Rizky Putra Fhonna",
    "keahlian": "website",
    "jabatan": "Ketua Prodi",
    "status": "aktif"
}


###
DELETE http://localhost:5000/dosen/1




MATA KULIAH
###
GET http://localhost:5000/mata_kuliah


###
GET http://localhost:5000/mata_kuliah/1


###
POST http://localhost:5000/rps
Content-Type: application/json

{
    "name": "Pemograman Web 1",
    "semester": "semester 3",
    "file_rps": "   "
}


###
PATCH  http://localhost:5000/mata_kuliah/1
Content-Type: application/json

{
    "name": "Pemograman Web 1",
    "sks": "3 SKS",
    "semester": "Semester 3"
}


###
DELETE http://localhost:5000/mata_kuliah/1